=== Beto-Massud/cartasig_QFieldCloud/docker-qgis/schemas/deltafile_01.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://opengis.ch/schemas/deltafile.json",
    "type": "object",
    "title": "Delta File Schema",
    "description": "TODO",
    "additionalProperties": false,
    "required": [
        "version",
        "projectId",
        "id",
        "deltas",
        "files"
    ],
    "definitions": {
        "delta_method_descr": {
            "type": "object",
            "title": "Delta Method Description",
            "description": "The actual changes to be applied to the feature. If 'geometry' is provided, it completely replaces the old one. If 'attributes' provided, it merges the contents with the already existing feature using https://tools.ietf.org/html/rfc7386",
            "additionalProperties": false,
            "properties": {
                "geometry": {
                    "type": "string",
                    "title": "Geometry",
                    "description": "Feature's geometry serialized in WKT. GeoJSON has a number of limitations so it was reconsidered.",
                    "format": "wkt",
                    "examples": [
                        "POINT (30 10)",
                        "LINESTRING (30 10, 10 30, 40 40)",
                        "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))",
                        "MULTIPOINT ((10 40), (40 30), (20 20), (30 10))"
                    ]
                },
                "attributes": {
                    "type": "object",
                    "title": "Attributes",
                    "description": "Feature's attributes to be changed. The rest of the properties are ignored.",
                    "examples": [
                        {
                            "prop1": "new contents"
                        }
                    ],
                    "additionalProperties": true
                }
            }
        }
    },
    "properties": {
        "version": {
            "type": "string",
            "title": "The Deltas File Format Version",
            "description": "Currently the only allowed value is 1.0, but in the future there might be newer minor or major versions.",
            "enum": [
                "1.0"
            ]
        },
        "projectId": {
            "type": "string",
            "format": "uuid",
            "title": "Project ID",
            "description": "The project ID that is current open on QField.",
            "examples": [
                "bbdc0a1b-ade9-4c3d-ad28-59d8f0347689"
            ]
        },
        "id": {
            "type": "string",
            "title": "Delta File ID",
            "description": "The delta file ID generated on the client to distinguish requests.",
            "format": "uuid",
            "examples": [
                "73544c91-6a55-483c-b0af-944c4846c49f"
            ]
        },
        "deltas": {
            "type": "array",
            "title": "Deltas",
            "description": "A list of the deltas to be applied sent to the server.",
            "additionalItems": true,
            "items": {
                "type": "object",
                "title": "A Single Delta",
                "description": "Describes the changes to be applied to a single feature.",
                "additionalProperties": true,
                "required": [
                    "fid",
                    "layerId",
                    "method"
                ],
                "properties": {
                    "fid_NOT_ENABLED_UNTIL_FID_IS_UUID": {
                        "type": "string",
                        "title": "Feature ID Schema",
                        "description": "To be able to unique identify features in the layers, we assign UUID as feature ID. We use UUID instead of sequential integer, so we can assign the value on QField, before sending it back to the server.",
                        "format": "uuid",
                        "examples": [
                            "ddc41fa4-3961-4127-80f6-7d3e3f3f985b"
                        ]
                    },
                    "layerId": {
                        "type": "string",
                        "title": "Layer ID",
                        "description": "The layer ID is the same as in the QGIS project file. Each delta file is responsible for a single layer.",
                        "examples": [
                            "e933b5aa-6ccb-416f-83e7-5a2ece85cf1a_LayerName"
                        ]
                    },
                    "method": {
                        "type": "string",
                        "title": "Method",
                        "description": "What type of operation to be applied to the feature.\n'create' - creates new feature\n'patch' - modifies certain values in an existing feature\n'delete' - deletes an existing feature",
                        "enum": ["create", "patch", "delete"]
                    },
                    "old": {
                        "$ref": "#/definitions/delta_method_descr"
                    },
                    "new": {
                        "$ref": "#/definitions/delta_method_descr"
                    }
                }
            }
        },
        "files": {
            "type": "array",
            "title": "Files",
            "description": "A list of the files to be uploaded to the server.",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "title": "Filename",
                "description": "Filename with path relative to project root",
                "example": "DCIM/photo1.jpg"
            }
        }
    }
}

=== Beto-Massud/cartasig_QFieldCloud/web-app/qfieldcloud/apps/api/tests/testdata/delta/deltas/singlelayer_singledelta_conflict.json
{
    "deltas": [
        {
            "fid": 1,
            "layerId": "points_c2784cf9_c9c3_45f6_9ce5_98a6047e4d6c",
            "method": "patch",
            "new": {
                "attributes": {
                    "int": 666
                }
            },
            "old": {
                "attributes": {
                    "int": 134
                }
            }
        }
    ],
    "files": [],
    "id": "6f109cd3-f44c-41db-b134-5f38468b9fda",
    "projectId": "e02d02cc-af1b-414c-a14c-e2ed5dfee52f",
    "version": "1.0"
}
